name: linting, testing. biulding
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit tests
        run: npm run test:unit
        if: always()
      - name: build storybook
        run: npm storybook:build
        if: always()
      - name: ui tests
        run: npm run test:ui:ci
        if: always()
